name: Deploy Svelte with GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install
        run: npm install
      - name: Check
        run: npm run check && npm run lint
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: svelte
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-svelte]
    steps:
      - uses: actions/download-artifact@v4
      - name: Unpack artefacts
        run: |
          mkdir build
          mv svelte/* build
      - name: Debug
        run: ls -R
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - uses: actions/deploy-pages@v4
        id: deployment
